Repository jenkins-x-apps/jx-app-datadog, pull requests merged in 2019-07, with the labels that each got.

#2 fix: adapts schema according to expected values.yml
  jx-app-datadog/values.schema.json
Labels: approved, lgtm, size/M

#3 feat: add options to enable Kubernetes events collection
  jx-app-datadog/values.schema.json
Labels: approved, lgtm, size/S

#4 chore: remove -passthrough
  jx-app-datadog/values.schema.json
Labels: approved, size/XS
